name: Check
on: push
jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: everything
        run: npm run everything
