name: My first deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: create file "file-name.txt"
        run: echo "test text in file" > file-name.txt
