name: create and commit file
on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create file "new-file.txt"
        run: echo "This is new file created by GitHub Actions" > new-file.txt

      - name: Commit new file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add new-file.txt
          git commit -m "add new file created by gh actions"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
