name: My second workflow
on: [push]
jobs:
  joba1:
    runs-on: ubuntu-latest
    steps:
      - name: Print HW
        run: echo 'Hello World! Its a first stage'

  joba2:
    runs-on: ubuntu-latest
    needs: joba1
    steps:
      - name: Stage2
        run: echo 'Hello World! Its a second stage'

  joba3:
    runs-on: ubuntu-latest
    needs: joba2
    steps:
      - name: Stage3
        run: echo 'Hello World! Its a third stage'
  # kek comment
